apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ops-l2-monitoring
  name: 'alloy-apps'
  ## uid: 91dbdb3e-89df-4595-8d6b-22ae611a7d69
  resourceVersion: '445594761'
  generation: 2
  annotations:
    aa.orga.customer: mdemo
    deployment.kubernetes.io/revision: '2'
    aa.orga.users: awolff2
    aa.orga.created: '2026-01-14T12:33:57Z'
    aa.orga.unit: ref-130
    aa.orga.product: l2-monitoring-v2
    aa.orga.notify: '2026-03-05T09:34:19Z'
    aa.orga.state: test
    aa.orga.version: v0.8.1-rc2
    aa.orga.destroyed: '2026-03-05T09:34:19Z'
spec:
  selector:
    matchLabels:
      app: alloy-apps
  replicas: 0
  template:
    metadata:
      labels:
        app: alloy-apps
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc/demo/alloy:v1.10.0
          ports:
            - containerPort: 12345
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600