kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana-apps
  namespace: ops-l2-monitoring
  ## uid: 9f78d25a-e380-44d3-9ff5-7c0f3a374087
  resourceVersion: '445577961'
  generation: 2
  creationTimestamp: '2026-01-14T12:57:42Z'
  annotations:
    aa.orga.customer: mdemo
    deployment.kubernetes.io/revision: '1'
    aa.orga.users: awolff2
    aa.orga.created: '2026-01-14T12:33:57Z'
    aa.orga.unit: ref-130
    aa.orga.product: l2-monitoring-v2
    aa.orga.notify: '2026-03-05T09:34:19Z'
    aa.orga.state: test
    aa.orga.version: v0.8.1-rc2
    aa.orga.destroyed: '2026-03-05T09:34:19Z'
spec:
  replicas: 0
  selector:
    matchLabels:
      app: grafana-apps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-apps
    spec:
      containers:
        - name: container
          image: 'image-registry.openshift-image-registry.svc/demo/grafana:main'
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
