kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus-apps
  namespace: ops-l2-monitoring
  uid: d41c6695-1753-4d6f-a6a6-03cd704fe101
  resourceVersion: '445544544'
  generation: 3
  creationTimestamp: '2026-01-14T12:40:49Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
    aa.orga.customer: 'mdemo'
    aa.orga.users: 'awolff2'
    aa.orga.created: '2026-01-14T12:33:57Z'
    aa.orga.unit: 'ref-130'
    aa.orga.product: 'l2-monitoring-v2'
    aa.orga.state: 'test'
    aa.orga.version: 'v0.8.1-rc2'
    aa.orga.notify: '2026-03-05T09:34:19Z'
    aa.orga.destroyed: '2026-03-05T09:34:19Z'
spec:
  # replicas: 2
  replicas: 0
  selector:
    matchLabels:
      app: prometheus-apps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-apps
    spec:
      containers:
        - name: container
          image: 'image-registry.openshift-image-registry.svc/demo/prometheus:v3.5.0'
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 2
  updatedReplicas: 2
  unavailableReplicas: 2
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2026-01-14T12:40:49Z'
      lastTransitionTime: '2026-01-14T12:40:49Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2026-01-14T12:40:49Z'
      lastTransitionTime: '2026-01-14T12:40:49Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "prometheus-apps-6b997cc595" is progressing.
